module DecoderTests exposing (suite)

import Dict
import Expect
import Fixtures
import Json.Decode as Decode
import Test exposing (..)
import Types exposing (..)


expectTrue : String -> Bool -> Expect.Expectation
expectTrue label value =
    Expect.equal True value |> Expect.onFail label


{-| The bundled fixtures are real engine output (generated by the server's
fixture dump); decoding them here keeps the Elm API boundary honest.
-}
suite : Test
suite =
    describe "contract decoders"
        [ test "session state decodes from engine fixture" <|
            \_ ->
                case Decode.decodeString sessionState Fixtures.sessionStateJson of
                    Ok state ->
                        Expect.all
                            [ \s -> Expect.equal s.worldName "Fixture World"
                            , \s -> Expect.equal s.session.characterName "Wren"
                            , \s -> Expect.equal s.session.version 0
                            , \s -> Expect.equal (List.length s.reachable) 6
                            , \s -> Expect.equal s.session.creatorPolicy.tablePreview True
                            ]
                            state

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        , test "map decodes with hexes, markers, and legend" <|
            \_ ->
                case Decode.decodeString mapData Fixtures.mapJson of
                    Ok data ->
                        Expect.all
                            [ \d -> expectTrue "expected discovered hexes" (List.length d.hexes > 1)
                            , \d -> expectTrue "expected markers somewhere" (List.any (\h -> not (List.isEmpty h.markers)) d.hexes)
                            , \d -> expectTrue "expected legend entries" (not (Dict.isEmpty d.legend))
                            ]
                            data

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        , test "history decodes chronological log entries" <|
            \_ ->
                case Decode.decodeString historyResponse Fixtures.historyJson of
                    Ok history ->
                        let
                            seqs =
                                List.map .seq history.entries
                        in
                        Expect.all
                            [ \_ -> expectTrue "expected entries" (List.length history.entries > 3)
                            , \_ -> Expect.equal seqs (List.sort seqs)
                            ]
                            ()

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        , test "command response decodes nested roll trace" <|
            \_ ->
                case Decode.decodeString commandResponse Fixtures.travelEncounterJson of
                    Ok response ->
                        Expect.all
                            [ \r -> Expect.equal r.resolution.outcome "encounter"
                            , \r -> expectTrue "expected several rolls in one trace" (List.length r.resolution.rolls >= 2)
                            , \r -> expectTrue "expected pending choices" (r.session.pendingEncounter /= Nothing)
                            ]
                            response

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        , test "combat presentation surface and opponent label come from content" <|
            \_ ->
                case Decode.decodeString commandResponse Fixtures.travelEncounterJson of
                    Ok response ->
                        case response.session.pendingEncounter of
                            Nothing ->
                                Expect.fail "expected a pending encounter"

                            Just pending ->
                                let
                                    combatants =
                                        List.filter
                                            (\c -> c.presentation /= Nothing)
                                            pending.choices

                                    plain =
                                        List.filter
                                            (\c -> c.presentation == Nothing)
                                            pending.choices
                                in
                                Expect.all
                                    [ \_ ->
                                        Expect.equal
                                            (List.map .presentation combatants)
                                            [ Just Battlefield ]
                                    , \_ ->
                                        expectTrue
                                            "expected non-combat choices to declare no surface"
                                            (List.length plain >= 1)
                                    , \_ ->
                                        Expect.equal pending.assetLabel (Just "Bandits")
                                    , \_ ->
                                        expectTrue
                                            "expected an authored asset reference"
                                            (pending.asset /= Nothing)
                                    ]
                                    ()

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        , test "unknown choice presentation surfaces are rejected" <|
            \_ ->
                let
                    bad =
                        "[{\"encounterId\":\"e\",\"tableId\":\"t\",\"tableVersion\":1,"
                            ++ "\"text\":\"x\",\"choices\":[{\"id\":\"c\",\"label\":\"L\","
                            ++ "\"table\":{\"id\":\"a\",\"version\":1},"
                            ++ "\"presentation\":\"battlefeild\"}],"
                            ++ "\"startedTick\":0,\"hex\":{\"q\":0,\"r\":0}}]"
                in
                case Decode.decodeString pendingEncounter bad of
                    Ok _ ->
                        Expect.fail "expected a misspelled presentation surface to fail decoding"

                    Err _ ->
                        Expect.pass
        , test "tables list decodes" <|
            \_ ->
                case Decode.decodeString tableList Fixtures.tablesJson of
                    Ok tables ->
                        expectTrue "expected core tables"
                            (List.any (\t -> t.id == "core/travel-encounter") tables)

                    Err err ->
                        Expect.fail (Decode.errorToString err)
        ]
